fix: default project banner
kreate-community/kreate-web pull request #155
Opened 2023-03-21 17:26 UTC by sk-tenba

2023-03-21 17:26 UTC, sk-tenba commented
![image](https://user-images.githubusercontent.com/110231356/226692156-96ffc5ba-80a6-45a3-9e87-661eac94c943.png)

2023-03-22 00:53 UTC, sk-kitsune commented on modules/teiki-components/components/PanelProjectOverviewV2/components/BannerCarousel/index.tsx
> +              )}
A bit opinionated but I want to use the default image only if the length is 0

Note that `numBoxes` can be set to _any_ integer larger than `items.length`, although I did not document it.

Suggestion: change from `<ImageView />` to `!index ? <ImageView ... /> : null`

2023-03-22 00:54 UTC, sk-kitsune commented on modules/teiki-components/components/PanelProjectOverviewV2/components/BannerCarousel/index.tsx
> +import { DEFAULT_IMAGE_URL } from "../../../../../../containers/PageHome/components/ProjectImageCropped/constants";
please copy this const to this folder

---

🔴 **Blocking issue**: this PR cannot be merged until this issue is resolved.

2023-03-22 00:54 UTC, sk-kitsune requested changes
⛔ **Changes requested**: there are blocking issues.

2023-03-22 02:49 UTC, sk-kitsune approved these changes
✅ **Approved**: no blocking issues

2023-03-22 02:55 UTC, merged