feat: change project tag from anchor to span
kreate-community/kreate-web pull request #166
Opened 2023-03-23 03:16 UTC by sk-gachou

Resolves: https://app.asana.com/0/1203842063837585/1204223774581484/f

2023-03-23 03:21 UTC, sk-gachou commented on containers/PageHome/components/ProjectTagList/index.tsx
> +                    e.preventDefault();
This line is to prevent browser from triggering the outer anchor tag (read asana task for more context). This is a bit ugly as I can't use stopPropagation. By the time the event reaches our React's event handler, it already passed through the outer anchor tag.

I don't know if it's gonna cause any troubles down the line.

2023-03-23 17:26 UTC, sk-kitsune commented on containers/PageHome/components/ProjectTagList/index.tsx
> +                    e.preventDefault();
🔴 **Blocking issue**: this PR cannot be merged until this issue is resolved.

2023-03-23 17:27 UTC, sk-kitsune requested changes
⛔ **Changes requested**: there are blocking issues.

2023-03-24 05:20 UTC, sk-gachou commented on containers/PageHome/components/ProjectTagList/index.tsx
> +                    e.preventDefault();
updated

2023-03-24 05:36 UTC, sk-kitsune submitted a review, later dismissed
✅ **Approved**: no blocking issues

2023-03-24 12:09 UTC, sk-kitsune approved these changes
✅ **Approved**: no blocking issues

2023-03-24 12:09 UTC, merged