fix: entry point page mint by color picker
kreate-community/kreate-web pull request #280
Opened 2023-03-30 17:15 UTC by sk-tenba

2023-03-30 17:16 UTC, sk-tenba commented
![figure1](https://user-images.githubusercontent.com/110231356/228914288-8cfe758a-71bf-4989-8730-f605f3ef4a3c.png)

2023-03-30 17:16 UTC, sk-tenba commented
![figure3](https://user-images.githubusercontent.com/110231356/228914349-b5fb0a2e-1414-4834-98be-906251dc8abf.png)

2023-03-30 17:40 UTC, sk-kitsune commented on containers/PageKolours/containers/Menu$TopNavigation/index.tsx
> +        <div className={styles.currentNav}>The Origin of Kolours</div>
My suggestion is to define `Menu$TopNavigation` at `teiki-components` as:

```
type Item = { label: string; key: string; href: string; }
function Menu$TopNavigation(props: { items: Item[], activeKey: string });
```

Basically, I am trying to copy from https://ant.design/components/menu

2023-03-30 17:41 UTC, sk-kitsune commented on containers/PageMintByColorPicker/index.module.scss
> +  display: flex;
```
display: block;
display: flex;
```


?????

2023-03-30 17:43 UTC, sk-kitsune commented on containers/PageKolours/containers/Menu$TopNavigation/index.module.scss
> +  color: colors.$black80;
hover and nothing changes?

2023-03-30 17:50 UTC, sk-kitsune commented on containers/PageMintByColorPicker/index.module.scss
> +  flex: 1 1 0;
This part looks like too much structural changes just to make the footer panel sticks to the bottom.

I suggest a less intrusive way:

```
.main {
  min-height: calc(100vh - 200px);
}
```

2023-03-30 17:50 UTC, sk-kitsune requested changes
⛔ **Changes requested**: there are blocking issues.

2023-03-31 03:54 UTC, sk-tenba commented
[Screencast from 31-03-2023 10:54:05.webm](https://user-images.githubusercontent.com/110231356/229018763-636b9357-3dab-4838-bc97-08b83866f18b.webm)

2023-03-31 03:55 UTC, sk-tenba commented
[Screencast from 31-03-2023 10:54:25.webm](https://user-images.githubusercontent.com/110231356/229018795-81cbe3bb-611b-4da1-bdec-39a2732318d9.webm)

2023-03-31 04:10 UTC, sk-kitsune approved these changes
✅ **Approved**: no blocking issues

2023-03-31 04:11 UTC, merged