feat: integrate ada handle
kreate-community/kreate-web pull request #85
Opened 2023-03-15 12:04 UTC by sk-tenba

2023-03-15 12:05 UTC, sk-tenba commented
![image](https://user-images.githubusercontent.com/110231356/225303909-362eb128-0a51-457a-b17b-e8f04e4aa31d.png)

2023-03-15 14:43 UTC, sk-kitsune commented on modules/ada-handle/hooks/useAdaHandle.ts
> +  }, []);
If this is the only reason why this hook exists, why don't we just move this code to `modules/ada-handle/utils.ts`?

2023-03-15 14:46 UTC, sk-kitsune commented on modules/ada-handle/hooks/useAdaHandle.ts
> +  }, []);
`setInterval` does not wait for the _async_ callback to be fulfilled.

If each query takes > 500ms to be fulfilled, two queries might overlap. Is that what we want?

2023-03-15 14:50 UTC, sk-kitsune commented on modules/ada-handle/hooks/useAdaHandle.ts
> +  }, []);
You can seek advice from @sk-shishi for a comparison between polling and other methods. There is a much better way (which is also not too complex).

2023-03-15 14:51 UTC, sk-kitsune commented on modules/ada-handle/hooks/useAdaHandle.ts
> +  }, []);
🔴 **Blocking issue**: this PR cannot be merged until this issue is resolved.

-----

This is a blocking issue because in the current implementation, we don't need `useAdaHandle` at all.

2023-03-15 14:54 UTC, sk-kitsune commented on modules/ada-handle/utils.ts
> +  queue.length = 0;
`const copiedQueue = queue.splice(0)`

I rarely see anyone write `queue.length = 0;`

2023-03-15 14:55 UTC, sk-kitsune commented on modules/ada-handle/utils.ts
> +        .filter((address) => !Object.keys(handles).includes(address))
`Object.keys(handles).includes(address)`

is equivalent to

`address in handles`

2023-03-15 14:56 UTC, sk-kitsune commented on modules/ada-handle/utils.ts
> +  });
What if `addresses` contains too many items. Note that url has its limit.

2023-03-15 14:56 UTC, sk-kitsune commented on modules/ada-handle/utils.ts
> +  copiedQueue.map(({ address, resolve }) => {
use `forEach` instead of `map` if the result is unused

2023-03-15 14:58 UTC, sk-kitsune commented on modules/teiki-ui/components/InlineAddress/index.tsx
> +  );
`useSWR` is a more appropriate here.

Currently, `deps` is `[]`. It means `handle` will not change when `value` changes.

----


🔴 **Blocking issue**: this PR cannot be merged until this issue is resolved.

2023-03-15 15:00 UTC, sk-kitsune commented on modules/teiki-ui/components/InlineAddress/index.tsx
> +      : prefixLength + suffixLength >= value.length
We need to handle the case where the `handle` is too long.

Please ask our designer for advice.

----

🔴 **Blocking issue**: this PR cannot be merged until this issue is resolved.

2023-03-19 02:55 UTC, sk-tenba commented
![image](https://user-images.githubusercontent.com/110231356/226151128-f2e3a02b-668e-41c9-a4df-2283989a7af4.png)

2023-03-19 04:00 UTC, sk-kitsune commented on modules/ada-handle/utils.ts
> +  const itemsToExecute = queue.splice(0, numItemToExecute);
equivalent to `const itemsToExecute = queue.splice(0, BATCH_LIMIT);`

2023-03-19 04:01 UTC, sk-kitsune commented on modules/ada-handle/utils.ts
> +        .filter((address) => !(address in handles))
`handles` is a `Map`, not an object

`address in handlers` is incorrect.


https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

---
🔴 **Blocking issue**: this PR cannot be merged until this issue is resolved.

2023-03-19 04:02 UTC, sk-kitsune commented on modules/ada-handle/utils.ts
> +    addresses: Array.from(new Set(filteredItems)),
`filteredItems` already contains unique items

2023-03-19 04:10 UTC, sk-kitsune commented on modules/ada-handle/utils.ts
> +}
1. Rename to `execAdaHandle` to `execute` or `run`.
2. Rename `execNextBatch` to `scheduleExecution` or `scheduleRunner`. The current name `execNextBatch` is misleading.
3. The guarding condition is unnecessary (the if statement). Exercise: prove that by replacing the `if` statement by `execAdaHandle();`, two _meaningful_ consecutive calls of `execAdaHandle()` will separated by at least `ADA_HANDLE_REFRESH_INTERVAL`. A call is _meaningful_ if `queue.length > 0`.

2023-03-19 04:12 UTC, sk-kitsune commented on modules/ada-handle/utils.ts
> +const BATCH_LIMIT = 50;
why 50? why did you choose this value?

2023-03-19 04:12 UTC, sk-kitsune requested changes
⛔ **Changes requested**: there are blocking issues.

2023-03-20 04:24 UTC, sk-kitsune commented on modules/ada-handle/utils.ts
> +const BATCH_LIMIT = 16;
Please add a comment to explain why we have this limit.

2023-03-20 04:26 UTC, sk-kitsune commented on modules/ada-handle/utils.ts
> +const ADA_HANDLE_REFRESH_INTERVAL = 200;
Rename to `EXECUTION_DELAY` or `BATCHING_DELAY`.

"_REFRESH_" is misleading.

---

🔴 **Blocking issue**: this PR cannot be merged until this issue is resolved.

2023-03-20 04:33 UTC, sk-kitsune commented on modules/ada-handle/utils.ts
> +  const itemsToExecute = queue.splice(0, BATCH_LIMIT);
`if (!itemsToExecute.length) return;`

2023-03-20 04:35 UTC, sk-kitsune commented on modules/ada-handle/utils.ts
> +const handles: Map<string, string> = new Map();
```
type Handle = string;

const addressToHandle: Map<Address, Handle> = new Map();
```


Using infix `-To-` to denote a mapping.

2023-03-20 04:37 UTC, sk-kitsune requested changes
⛔ **Changes requested**: there are blocking issues.

---

The rest lgtm.

2023-03-20 04:51 UTC, sk-kitsune approved these changes
✅ **Approved**: no blocking issues

2023-03-20 04:52 UTC, merged